
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Dec  9 2019 08:09:54 -02 (Dec  9 2019 10:09:54 UTC)

// Verification Directory fv/mac4 

module add_unsigned(A, B, Z, clk, Q, reset, Q_1);
  input [15:0] A, B;
  input clk, Q, reset, Q_1;
  output [15:0] Z;
  wire [15:0] A, B;
  wire clk, Q, reset, Q_1;
  wire [15:0] Z;
  wire UNCONNECTED, n_2, n_3, n_6, n_8, n_9, n_10, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_82, n_83, n_137, n_139;
  HS65_GS_MUX21I1X6 g2695__8780(.D0 (n_70), .D1 (n_70), .S0 (n_41), .Z
       (Z[14]));
  HS65_GS_OA12X18 g2697__4296(.A (n_24), .B (n_68), .C (n_29), .Z
       (n_70));
  HS65_GSS_XNOR2X6 g2698__3772(.A (n_49), .B (n_68), .Z (Z[13]));
  HS65_GS_OAI12X12 g2700__1474(.A (n_31), .B (n_66), .C (n_21), .Z
       (n_68));
  HS65_GSS_XNOR2X6 g2701__4547(.A (n_48), .B (n_67), .Z (Z[12]));
  HS65_GS_IVX7 g2702(.A (n_66), .Z (n_67));
  HS65_GS_OA12X18 g2703__9682(.A (n_30), .B (n_64), .C (n_17), .Z
       (n_66));
  HS65_GS_IVX7 g2706(.A (n_64), .Z (n_65));
  HS65_GS_AOI12X12 g2707__2683(.A (n_28), .B (n_62), .C (n_19), .Z
       (n_64));
  HS65_GS_MUX21I1X6 g2708__1309(.D0 (n_63), .D1 (n_63), .S0 (n_51), .Z
       (Z[10]));
  HS65_GS_BFX9 g2709(.A (n_62), .Z (n_63));
  HS65_GS_OAI12X12 g2710__6877(.A (n_34), .B (n_60), .C (n_23), .Z
       (n_62));
  HS65_GS_MUX21I1X6 g2711__2900(.D0 (n_61), .D1 (n_61), .S0 (n_39), .Z
       (Z[9]));
  HS65_GS_BFX9 g2712(.A (n_60), .Z (n_61));
  HS65_GS_AOI12X12 g2713__2391(.A (n_32), .B (n_9), .C (n_18), .Z
       (n_60));
  HS65_GS_MUX21I1X6 g2714__7675(.D0 (n_9), .D1 (n_9), .S0 (n_42), .Z
       (Z[8]));
  HS65_GS_OAI12X18 g2716__7118(.A (n_38), .B (n_59), .C (n_14), .Z
       (n_9));
  HS65_GSS_XNOR2X6 g2717__8757(.A (n_44), .B (n_59), .Z (Z[7]));
  HS65_GS_OA12X18 g2718__1786(.A (n_27), .B (n_57), .C (n_10), .Z
       (n_59));
  HS65_GS_BFX9 g2721(.A (n_57), .Z (n_58));
  HS65_GS_OAI12X6 g2722__5953(.A (n_56), .B (n_22), .C (n_35), .Z
       (n_57));
  HS65_GSS_XNOR2X6 g2723__5703(.A (n_45), .B (n_56), .Z (Z[5]));
  HS65_GS_OAI12X12 g2724__7114(.A (n_36), .B (n_8), .C (n_15), .Z
       (n_56));
  HS65_GS_AOI12X12 g2728__2250(.A (n_37), .B (n_137), .C (n_16), .Z
       (n_8));
  HS65_GSS_XNOR2X6 g2729__6083(.A (n_43), .B (n_137), .Z (Z[3]));
  HS65_GSS_XOR3X2 g2730__2703(.A (A[2]), .B (n_76), .C (n_52), .Z
       (Z[2]));
  HS65_GS_OAI21X3 g2733__7344(.A (n_13), .B (n_33), .C (n_20), .Z
       (n_52));
  HS65_GSS_XNOR2X6 g2734__1840(.A (n_13), .B (n_50), .Z (Z[1]));
  HS65_GS_NAND2AX7 g2735__5019(.A (n_19), .B (n_28), .Z (n_51));
  HS65_GS_NOR2AX3 g2736__1857(.A (n_20), .B (n_33), .Z (n_50));
  HS65_GS_NAND2AX7 g2737__9906(.A (n_24), .B (n_29), .Z (n_49));
  HS65_GS_NAND2AX7 g2738__8780(.A (n_31), .B (n_21), .Z (n_48));
  HS65_GS_NAND2AX7 g2739__4296(.A (n_30), .B (n_17), .Z (n_47));
  HS65_GS_NAND2AX7 g2740__3772(.A (n_36), .B (n_15), .Z (n_46));
  HS65_GS_NAND2AX7 g2741__1474(.A (n_22), .B (n_35), .Z (n_45));
  HS65_GS_OA12X9 g2742__4547(.A (n_73), .B (A[0]), .C (n_13), .Z
       (Z[0]));
  HS65_GS_NOR2AX3 g2744__2683(.A (n_14), .B (n_38), .Z (n_44));
  HS65_GS_NAND2AX7 g2745__1309(.A (n_16), .B (n_37), .Z (n_43));
  HS65_GS_NAND2AX7 g2746__6877(.A (n_18), .B (n_32), .Z (n_42));
  HS65_GS_MUX21I1X6 g2747__2900(.D0 (B[14]), .D1 (B[14]), .S0 (A[14]),
       .Z (n_41));
  HS65_GS_NOR2AX3 g2749__7675(.A (n_23), .B (n_34), .Z (n_39));
  HS65_GS_NOR2X6 g2750__7118(.A (A[6]), .B (n_75), .Z (n_27));
  HS65_GS_NOR2X6 g2753__5953(.A (A[7]), .B (n_78), .Z (n_38));
  HS65_GS_OR2X9 g2754__5703(.A (n_72), .B (A[3]), .Z (n_37));
  HS65_GS_NOR2X6 g2755__7114(.A (n_74), .B (A[4]), .Z (n_36));
  HS65_GS_OR2X9 g2756__5266(.A (A[5]), .B (n_71), .Z (n_35));
  HS65_GS_NOR2X6 g2757__2250(.A (A[9]), .B (n_80), .Z (n_34));
  HS65_GS_NOR2X6 g2758__6083(.A (n_77), .B (A[1]), .Z (n_33));
  HS65_GS_OR2X9 g2759__2703(.A (A[8]), .B (n_79), .Z (n_32));
  HS65_GS_NOR2X6 g2760__5795(.A (A[12]), .B (B[12]), .Z (n_31));
  HS65_GS_NOR2X6 g2761__7344(.A (A[11]), .B (B[11]), .Z (n_30));
  HS65_GS_OR2X9 g2762__1840(.A (A[13]), .B (B[13]), .Z (n_29));
  HS65_GS_OR2X9 g2763__5019(.A (A[10]), .B (B[10]), .Z (n_28));
  HS65_GS_NAND2X7 g2766__8780(.A (A[6]), .B (n_75), .Z (n_10));
  HS65_GS_AND2X4 g2767__4296(.A (B[13]), .B (A[13]), .Z (n_24));
  HS65_GS_NAND2X7 g2768__3772(.A (A[9]), .B (n_80), .Z (n_23));
  HS65_GS_AND2X4 g2769__1474(.A (n_71), .B (A[5]), .Z (n_22));
  HS65_GS_NAND2X7 g2770__4547(.A (A[12]), .B (B[12]), .Z (n_21));
  HS65_GS_NAND2X7 g2771__9682(.A (n_77), .B (A[1]), .Z (n_20));
  HS65_GS_AND2X4 g2772__2683(.A (B[10]), .B (A[10]), .Z (n_19));
  HS65_GS_AND2X4 g2773__1309(.A (n_79), .B (A[8]), .Z (n_18));
  HS65_GS_NAND2X7 g2774__6877(.A (A[11]), .B (B[11]), .Z (n_17));
  HS65_GS_AND2X4 g2775__2900(.A (A[3]), .B (n_72), .Z (n_16));
  HS65_GS_NAND2X7 g2776__2391(.A (n_74), .B (A[4]), .Z (n_15));
  HS65_GS_NAND2X7 g2777__7675(.A (A[7]), .B (n_78), .Z (n_14));
  HS65_GS_NAND2X7 g2778__7118(.A (n_73), .B (A[0]), .Z (n_13));
  HS65_GSS_XNOR2X6 g2__8757(.A (n_65), .B (n_47), .Z (Z[11]));
  HS65_GS_SDFPSQTX9 retime_s3_2_reg(.SN (reset), .CP (clk), .D (n_139),
       .TI (n_82), .TE (n_2), .Q (n_82), .TQ (UNCONNECTED));
  HS65_GS_SDFPRQX9 retime_s3_1_reg(.RN (reset), .CP (clk), .D (n_6),
       .TI (n_83), .TE (n_2), .Q (n_83));
  HS65_GS_SDFPQX4 retime_s2_12_reg(.CP (clk), .D (B[8]), .TI (n_79),
       .TE (n_3), .Q (n_79));
  HS65_GS_SDFPQX9 retime_s2_20_reg(.CP (clk), .D (n_72), .TI (B[3]),
       .TE (Q_1), .Q (n_72));
  HS65_GS_SDFPQX9 retime_s2_7_reg(.CP (clk), .D (B[9]), .TI (n_80), .TE
       (n_3), .Q (n_80));
  HS65_GS_SDFPQX9 retime_s2_21_reg(.CP (clk), .D (n_71), .TI (B[5]),
       .TE (Q_1), .Q (n_71));
  HS65_GS_SDFPQX9 retime_s2_19_reg(.CP (clk), .D (n_73), .TI (B[0]),
       .TE (Q_1), .Q (n_73));
  HS65_GS_SDFPQX9 retime_s2_15_reg(.CP (clk), .D (n_77), .TI (B[1]),
       .TE (Q_1), .Q (n_77));
  HS65_GS_SDFPQX9 retime_s2_16_reg(.CP (clk), .D (n_76), .TI (B[2]),
       .TE (Q_1), .Q (n_76));
  HS65_GS_SDFPQX9 retime_s2_17_reg(.CP (clk), .D (n_75), .TI (B[6]),
       .TE (Q_1), .Q (n_75));
  HS65_GS_SDFPQX9 retime_s2_18_reg(.CP (clk), .D (n_74), .TI (B[4]),
       .TE (Q_1), .Q (n_74));
  HS65_GS_SDFPQX9 retime_s2_13_reg(.CP (clk), .D (B[7]), .TI (n_78),
       .TE (n_3), .Q (n_78));
  HS65_GS_MUX21I1X6 g1938__5703(.D0 (B[15]), .D1 (B[15]), .S0 (A[15]),
       .Z (n_6));
  HS65_GS_IVX9 g1941(.A (Q_1), .Z (n_3));
  HS65_GS_IVX7 g1942(.A (Q), .Z (n_2));
  HS65_GS_XOR2X4 g2(.A (n_8), .B (n_46), .Z (Z[4]));
  HS65_GS_PAO2X18 g2780(.A (n_76), .B (A[2]), .P (n_52), .Z (n_137));
  HS65_GS_XNOR2X35 g2781(.A (n_83), .B (n_82), .Z (Z[15]));
  HS65_GS_PAO2X9 g2782(.A (A[14]), .B (B[14]), .P (n_70), .Z (n_139));
  HS65_GSS_XNOR3X2 g2783(.A (n_58), .B (A[6]), .C (n_75), .Z (Z[6]));
endmodule

module mult_unsigned(A, B, Z, clk, en, Q);
  input [7:0] A, B;
  input clk, en, Q;
  output [15:0] Z;
  wire [7:0] A, B;
  wire clk, en, Q;
  wire [15:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_28, n_29, n_31, n_32, n_33, n_34;
  wire n_35, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_162;
  wire n_164, n_165, n_166, n_167, n_168, n_170, n_172, n_175;
  wire n_176, n_177, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_187, n_188, n_189, n_191, n_192, n_194, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_222, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_235, n_254, n_255, n_256, n_257, n_259, n_260;
  wire n_262, n_263, n_269, n_273, n_282, n_283, n_284, n_287;
  wire n_290, n_293, n_294, n_295, n_297, n_298;
  HS65_GSS_XNOR2X6 g7001__2250(.A (n_192), .B (n_254), .Z (Z[9]));
  HS65_GS_IVX9 g7002(.A (n_199), .Z (Z[8]));
  HS65_GS_BDECNX4 g7003__6083(.DN (n_183), .DNM1 (n_184), .NDBL
       (n_287), .ZNN (n_188), .ZNP (n_189), .Z (n_199));
  HS65_GS_PAOI2X6 g7004__2703(.A (n_189), .B (n_184), .P (n_198), .Z
       (n_254));
  HS65_GS_IVX9 g7006(.A (n_287), .Z (n_198));
  HS65_GS_PAO2X18 g7011__5019(.A (n_162), .B (n_293), .P (n_191), .Z
       (n_194));
  HS65_GSS_XOR2X6 g7014__9906(.A (n_255), .B (n_205), .Z (n_192));
  HS65_GSS_XOR2X6 g7017__8780(.A (n_206), .B (n_180), .Z (n_205));
  HS65_GS_PAOI2X6 g7019__3772(.A (n_159), .B (n_167), .P (n_175), .Z
       (n_191));
  HS65_GS_IVX9 g7020(.A (n_188), .Z (n_189));
  HS65_GSS1_FA1X9 g7021__1474(.A0 (n_282), .B0 (n_165), .CI (n_298),
       .CO (n_255), .S0 (n_188));
  HS65_GS_NAND2AX7 g7022__4547(.A (n_185), .B (n_179), .Z (n_187));
  HS65_GS_IVX9 g7024(.A (n_183), .Z (n_184));
  HS65_GS_IVX9 g7025(.A (n_182), .Z (Z[14]));
  HS65_GS_IVX9 g7026(.A (n_181), .Z (Z[15]));
  HS65_GSS1_FA1X9 g7029__2683(.A0 (n_156), .B0 (n_170), .CI (n_166),
       .CO (n_183), .S0 (n_185));
  HS65_GS_FA1X4 g7030__1309(.A0 (n_227), .B0 (n_233), .CI (n_176), .CO
       (n_181), .S0 (n_182));
  HS65_GSS_XOR2X6 g7031__6877(.A (n_257), .B (n_256), .Z (n_180));
  HS65_GS_IVX9 g7033(.A (n_294), .Z (n_179));
  HS65_GS_IVX9 g7034(.A (n_177), .Z (Z[13]));
  HS65_GS_FA1X4 g7035__2900(.A0 (n_232), .B0 (n_231), .CI (n_157), .CO
       (n_176), .S0 (n_177));
  HS65_GSS_XNOR2X6 g7036__2391(.A (n_209), .B (n_168), .Z (n_206));
  HS65_GS_PAO2X9 g7038__7118(.A (n_148), .B (n_160), .P (n_164), .Z
       (n_175));
  HS65_GSS1_FA1X9 g7043__5953(.A0 (n_146), .B0 (n_115), .CI (n_135),
       .CO (n_170), .S0 (n_172));
  HS65_GSS_XNOR2X6 g7045__7114(.A (n_259), .B (n_207), .Z (n_168));
  HS65_GS_PAO2X9 g7046__5266(.A (n_131), .B (n_141), .P (n_154), .Z
       (n_256));
  HS65_GS_BDECNX9 g7047__2250(.DN (n_140), .DNM1 (n_121), .NDBL (n_55),
       .ZNN (n_150), .ZNP (n_149), .Z (n_167));
  HS65_GSS1_FA1X9 g7048__6083(.A0 (n_133), .B0 (n_129), .CI (n_134),
       .CO (n_165), .S0 (n_166));
  HS65_GS_PAOI2X6 g7050__2703(.A (n_106), .B (n_144), .P (n_137), .Z
       (n_164));
  HS65_GSS_XNOR2X6 g7052__7344(.A (n_208), .B (n_155), .Z (n_207));
  HS65_GS_PAO2X9 g7053__1840(.A (n_150), .B (n_121), .P (n_55), .Z
       (n_162));
  HS65_GS_CBI4I1X5 g7054__5019(.A (n_103), .B (n_138), .C (n_147), .D
       (n_145), .Z (n_257));
  HS65_GS_IVX9 g7056(.A (n_158), .Z (Z[12]));
  HS65_GSS1_FA1X9 g7057__9906(.A0 (n_290), .B0 (n_102), .CI (n_125),
       .CO (n_159), .S0 (n_160));
  HS65_GS_FA1X4 g7058__8780(.A0 (n_230), .B0 (n_226), .CI (n_297), .CO
       (n_157), .S0 (n_158));
  HS65_GSS_XNOR2X6 g7059__4296(.A (n_53), .B (n_151), .Z (n_156));
  HS65_GS_XNOR2X4 g7060__3772(.A (n_262), .B (n_260), .Z (n_155));
  HS65_GS_PAO2X9 g7062__4547(.A (n_104), .B (n_142), .P (n_119), .Z
       (n_154));
  HS65_GSS_XOR2X6 g7065__2683(.A (n_119), .B (n_142), .Z (n_151));
  HS65_GS_IVX9 g7067(.A (n_150), .Z (n_149));
  HS65_GS_IVX9 g7068(.A (n_130), .Z (n_148));
  HS65_GS_FA1X9 g7069__1309(.A0 (n_82), .B0 (n_65), .CI (n_80), .CO
       (n_146), .S0 (n_150));
  HS65_GS_NAND2X7 g7070__6877(.A (n_52), .B (n_139), .Z (n_145));
  HS65_GSS_XNOR2X6 g7071__2900(.A (n_77), .B (n_126), .Z (n_147));
  HS65_GS_PAOI2X6 g7072__2391(.A (n_71), .B (n_105), .P (n_117), .Z
       (n_144));
  HS65_GS_OAI21X3 g7073__7675(.A (n_124), .B (n_127), .C (n_128), .Z
       (n_143));
  HS65_GS_IVX7 g7074(.A (n_121), .Z (n_140));
  HS65_GS_IVX7 g7075(.A (n_139), .Z (n_138));
  HS65_GS_FA1X4 g7076__7118(.A0 (n_67), .B0 (n_66), .CI (n_62), .CO
       (n_142), .S0 (n_135));
  HS65_GS_FA1X4 g7077__8757(.A0 (n_63), .B0 (n_89), .CI (n_83), .CO
       (n_141), .S0 (n_134));
  HS65_GS_FA1X4 g7078__1786(.A0 (n_84), .B0 (n_64), .CI (n_81), .CO
       (n_139), .S0 (n_133));
  HS65_GS_MUX21I1X6 g7079__5953(.D0 (n_107), .D1 (n_107), .S0 (n_95),
       .Z (n_132));
  HS65_GS_PAO2X9 g7080__5703(.A (n_87), .B (n_203), .P (n_75), .Z
       (n_260));
  HS65_GSS_XNOR2X6 g7081__7114(.A (n_114), .B (n_112), .Z (n_137));
  HS65_GSS_XNOR2X6 g7082__5266(.A (n_122), .B (n_108), .Z (n_136));
  HS65_GSS_XOR3X2 g7083__2250(.A (n_105), .B (n_71), .C (n_117), .Z
       (Z[2]));
  HS65_GS_PAO2X9 g7084__6083(.A (n_90), .B (n_73), .P (n_123), .Z
       (n_129));
  HS65_GSS_XOR2X6 g7085__2703(.A (n_75), .B (n_116), .Z (n_131));
  HS65_GS_PAOI2X6 g7086__5795(.A (n_91), .B (n_93), .P (n_114), .Z
       (n_130));
  HS65_GS_NAND2X7 g7088__7344(.A (n_95), .B (n_107), .Z (n_128));
  HS65_GS_NOR2X6 g7089__1840(.A (n_95), .B (n_107), .Z (n_127));
  HS65_GS_CB4I6X9 g7090__5019(.A (n_202), .B (n_89), .C (n_118), .D
       (n_96), .Z (n_259));
  HS65_GS_XOR2X9 g7091__1857(.A (n_74), .B (n_118), .Z (n_126));
  HS65_GSS_XNOR2X6 g7092__9906(.A (n_263), .B (n_110), .Z (n_208));
  HS65_GSS_XOR2X6 g7093__8780(.A (n_210), .B (n_109), .Z (n_209));
  HS65_GSS_XNOR2X6 g7094__4296(.A (n_88), .B (n_111), .Z (n_125));
  HS65_GS_IVX9 g7096(.A (n_122), .Z (n_123));
  HS65_GS_HA1X9 g7097__3772(.A0 (n_72), .B0 (n_68), .CO (n_122), .S0
       (n_124));
  HS65_GS_PAO2X9 g7098__1474(.A (n_70), .B (n_88), .P (n_94), .Z
       (n_121));
  HS65_GS_NOR2X5 g7100__9682(.A (n_98), .B (n_105), .Z (Z[1]));
  HS65_GSS_XOR2X6 g7101__2683(.A (n_203), .B (n_87), .Z (n_116));
  HS65_GS_NAND2X7 g7102__1309(.A (n_99), .B (n_104), .Z (n_115));
  HS65_GS_NAND2AX7 g7103__6877(.A (n_100), .B (n_52), .Z (n_119));
  HS65_GS_NAND2X7 g7105__2900(.A (n_97), .B (n_262), .Z (n_118));
  HS65_GS_MUX21I1X6 g7106__2391(.D0 (n_78), .D1 (n_78), .S0 (n_57), .Z
       (n_117));
  HS65_GS_MUX21I1X6 g7108__7118(.D0 (n_91), .D1 (n_91), .S0 (n_92), .Z
       (n_112));
  HS65_GSS_XOR2X6 g7109__8757(.A (n_70), .B (n_94), .Z (n_111));
  HS65_GS_XNOR2X4 g7110__1786(.A (n_201), .B (n_204), .Z (n_110));
  HS65_GSS_XOR2X6 g7111__5953(.A (n_200), .B (n_202), .Z (n_109));
  HS65_GSS_XOR2X6 g7112__5703(.A (n_90), .B (n_73), .Z (n_108));
  HS65_GSS_XOR2X6 g7113__7114(.A (n_86), .B (n_85), .Z (n_114));
  HS65_GS_IVX9 g7115(.A (n_53), .Z (n_104));
  HS65_GS_IVX9 g7116(.A (n_52), .Z (n_103));
  HS65_GS_NAND2X7 g7117__5266(.A (n_79), .B (n_76), .Z (n_107));
  HS65_GS_NOR2X6 g7118__2250(.A (n_57), .B (n_88), .Z (n_102));
  HS65_GS_NAND2X7 g7120__6083(.A (n_58), .B (n_78), .Z (n_106));
  HS65_GS_AND2X9 g7121__2703(.A (Z[0]), .B (n_58), .Z (n_105));
  HS65_GSS_XOR2X6 g7124__5795(.A (n_224), .B (n_228), .Z (Z[10]));
  HS65_GS_AOI22X6 g7126__1840(.A (n_214), .B (n_217), .C (n_218), .D
       (n_59), .Z (n_100));
  HS65_GS_AO22X9 g7127__5019(.A (n_211), .B (n_217), .C (n_273), .D
       (n_218), .Z (n_99));
  HS65_GS_AOI22X4 g7128__1857(.A (n_222), .B (n_217), .C (n_269), .D
       (n_220), .Z (n_98));
  HS65_GS_AO22X9 g7129__9906(.A (n_212), .B (n_217), .C (n_219), .D
       (n_214), .Z (n_97));
  HS65_GS_AND2X4 g7130__8780(.A (n_77), .B (n_74), .Z (n_96));
  HS65_GS_IVX7 g7133(.A (n_92), .Z (n_93));
  HS65_GS_IVX9 g7136(.A (n_57), .Z (n_58));
  HS65_GS_NAND2X7 g7138__4296(.A (n_211), .B (n_220), .Z (n_95));
  HS65_GS_NAND2X5 g7139__3772(.A (n_269), .B (n_219), .Z (n_86));
  HS65_GS_NAND2X5 g7140__1474(.A (n_217), .B (n_61), .Z (n_85));
  HS65_GS_AND2X4 g7141__4547(.A (n_220), .B (n_222), .Z (Z[0]));
  HS65_GS_NAND2X7 g7142__9682(.A (n_213), .B (n_59), .Z (n_204));
  HS65_GS_NAND2X7 g7143__2683(.A (n_222), .B (n_215), .Z (n_94));
  HS65_GS_NAND2X7 g7144__1309(.A (n_213), .B (n_61), .Z (n_84));
  HS65_GS_NAND2X7 g7145__6877(.A (n_212), .B (n_220), .Z (n_83));
  HS65_GS_NAND2X7 g7146__2900(.A (n_211), .B (n_215), .Z (n_210));
  HS65_GS_NAND2X7 g7147__2391(.A (n_213), .B (n_222), .Z (n_82));
  HS65_GS_NAND2X7 g7148__7675(.A (n_219), .B (n_212), .Z (n_201));
  HS65_GS_NAND2X7 g7149__7118(.A (n_273), .B (n_215), .Z (n_81));
  HS65_GS_NAND2X7 g7150__8757(.A (n_218), .B (n_222), .Z (n_92));
  HS65_GS_AND2X4 g7151__1786(.A (n_273), .B (n_220), .Z (n_91));
  HS65_GS_NAND2X7 g7152__5953(.A (n_269), .B (n_215), .Z (n_80));
  HS65_GS_NAND2X7 g7153__5703(.A (n_214), .B (n_220), .Z (n_90));
  HS65_GS_NAND2X7 g7154__7114(.A (n_269), .B (n_216), .Z (n_89));
  HS65_GS_NAND2X7 g7155__5266(.A (n_269), .B (n_217), .Z (n_57));
  HS65_GS_NAND2X7 g7156__2250(.A (n_219), .B (n_61), .Z (n_88));
  HS65_GS_NAND2X7 g7157__6083(.A (n_213), .B (n_273), .Z (n_203));
  HS65_GS_NAND2X7 g7158__2703(.A (n_211), .B (n_218), .Z (n_87));
  HS65_GS_AND2X4 g7160__5795(.A (n_269), .B (n_218), .Z (n_79));
  HS65_GS_AND2X4 g7161__7344(.A (n_214), .B (n_217), .Z (n_69));
  HS65_GS_AND2X4 g7162__1840(.A (n_219), .B (n_222), .Z (n_78));
  HS65_GS_NAND2X7 g7163__5019(.A (n_216), .B (n_61), .Z (n_77));
  HS65_GS_AND2X4 g7164__1857(.A (n_218), .B (n_61), .Z (n_68));
  HS65_GS_NAND2X7 g7165__9906(.A (n_216), .B (n_273), .Z (n_200));
  HS65_GS_NAND2X7 g7166__8780(.A (n_219), .B (n_59), .Z (n_67));
  HS65_GS_AND2X9 g7167__4296(.A (n_217), .B (n_273), .Z (n_76));
  HS65_GS_NAND2X7 g7168__3772(.A (n_59), .B (n_215), .Z (n_75));
  HS65_GS_NAND2X7 g7169__1474(.A (n_269), .B (n_235), .Z (n_74));
  HS65_GS_NAND2X7 g7170__4547(.A (n_216), .B (n_222), .Z (n_73));
  HS65_GS_NAND2X7 g7171__9682(.A (n_269), .B (n_213), .Z (n_66));
  HS65_GS_NAND2X7 g7172__2683(.A (n_219), .B (n_273), .Z (n_65));
  HS65_GS_NAND2X7 g7173__1309(.A (n_214), .B (n_218), .Z (n_263));
  HS65_GS_AND2X4 g7174__6877(.A (n_217), .B (n_59), .Z (n_72));
  HS65_GS_NAND2X7 g7175__2900(.A (n_219), .B (n_211), .Z (n_64));
  HS65_GS_NAND2X7 g7176__2391(.A (n_235), .B (n_222), .Z (n_63));
  HS65_GS_AND2X4 g7177__7675(.A (n_220), .B (n_61), .Z (n_71));
  HS65_GS_NAND2X7 g7178__7118(.A (n_220), .B (n_59), .Z (n_70));
  HS65_GS_NAND2X7 g7179__8757(.A (n_215), .B (n_61), .Z (n_62));
  HS65_GS_NAND2X7 g7180__1786(.A (n_235), .B (n_61), .Z (n_202));
  HS65_GSS_XNOR2X6 g2__5953(.A (n_167), .B (n_56), .Z (Z[5]));
  HS65_GSS_XNOR2X6 g7185__7114(.A (n_159), .B (n_175), .Z (n_56));
  HS65_GSS_XOR2X6 g7189__2250(.A (n_124), .B (n_132), .Z (n_55));
  HS65_GS_NAND2AX7 g7191__2703(.A (n_201), .B (n_69), .Z (n_262));
  HS65_GS_NOR2AX6 g7192__5795(.A (n_76), .B (n_87), .Z (n_53));
  HS65_GS_NAND2AX7 g7193__7344(.A (n_263), .B (n_72), .Z (n_52));
  HS65_GSS_SDFPQX18 retime_s1_1_reg(.CP (clk), .D (n_235), .TI (B[7]),
       .TE (en), .Q (n_235));
  HS65_GS_SDFPQX9 retime_s1_2_reg(.CP (clk), .D (n_222), .TI (A[0]),
       .TE (en), .Q (n_222));
  HS65_GS_SDFPQX9 retime_s1_3_reg(.CP (clk), .D (n_61), .TI (A[2]), .TE
       (en), .Q (n_61));
  HS65_GS_SDFPQX9 retime_s1_4_reg(.CP (clk), .D (n_220), .TI (B[0]),
       .TE (en), .Q (n_220));
  HS65_GS_SDFPQX9 retime_s1_5_reg(.CP (clk), .D (n_269), .TI (A[1]),
       .TE (en), .Q (n_269));
  HS65_GSS_SDFPQX18 retime_s1_6_reg(.CP (clk), .D (n_219), .TI (B[2]),
       .TE (en), .Q (n_219));
  HS65_GS_SDFPQX9 retime_s1_7_reg(.CP (clk), .D (n_218), .TI (B[3]),
       .TE (en), .Q (n_218));
  HS65_GS_SDFPQX9 retime_s1_8_reg(.CP (clk), .D (n_217), .TI (B[1]),
       .TE (en), .Q (n_217));
  HS65_GSS_SDFPQX18 retime_s1_9_reg(.CP (clk), .D (n_216), .TI (B[6]),
       .TE (en), .Q (n_216));
  HS65_GS_SDFPQX9 retime_s1_10_reg(.CP (clk), .D (n_215), .TI (B[4]),
       .TE (en), .Q (n_215));
  HS65_GS_SDFPQX9 retime_s1_11_reg(.CP (clk), .D (n_214), .TI (A[6]),
       .TE (en), .Q (n_214));
  HS65_GS_SDFPQX9 retime_s1_12_reg(.CP (clk), .D (n_213), .TI (B[5]),
       .TE (en), .Q (n_213));
  HS65_GSS_SDFPQX18 retime_s1_13_reg(.CP (clk), .D (n_212), .TI (A[7]),
       .TE (en), .Q (n_212));
  HS65_GS_SDFPQX9 retime_s1_14_reg(.CP (clk), .D (n_273), .TI (A[3]),
       .TE (en), .Q (n_273));
  HS65_GS_SDFPQX9 retime_s1_15_reg(.CP (clk), .D (n_59), .TI (A[4]),
       .TE (en), .Q (n_59));
  HS65_GS_SDFPQX9 retime_s1_16_reg(.CP (clk), .D (n_211), .TI (A[5]),
       .TE (en), .Q (n_211));
  HS65_GS_SDFPQX9 retime_s2_1_reg(.CP (clk), .D (n_39), .TI (n_233),
       .TE (n_0), .Q (n_233));
  HS65_GS_SDFPQX9 retime_s2_2_reg(.CP (clk), .D (n_40), .TI (n_232),
       .TE (n_0), .Q (n_232));
  HS65_GS_SDFPQX9 retime_s2_3_reg(.CP (clk), .D (n_231), .TI (n_50),
       .TE (Q), .Q (n_231));
  HS65_GS_SDFPQX9 retime_s2_4_reg(.CP (clk), .D (n_230), .TI (n_51),
       .TE (Q), .Q (n_230));
  HS65_GS_SDFPQX9 retime_s2_5_reg(.CP (clk), .D (n_44), .TI (n_229),
       .TE (n_0), .Q (n_229));
  HS65_GS_SDFPQX9 retime_s2_6_reg(.CP (clk), .D (n_25), .TI (n_228),
       .TE (n_0), .Q (n_228));
  HS65_GS_SDFPQX9 retime_s2_8_reg(.CP (clk), .D (n_11), .TI (n_227),
       .TE (n_0), .Q (n_227));
  HS65_GS_SDFPQX9 retime_s2_9_reg(.CP (clk), .D (n_226), .TI (n_48),
       .TE (Q), .Q (n_226));
  HS65_GS_SDFPQX9 retime_s2_10_reg(.CP (clk), .D (n_225), .TI (n_49),
       .TE (Q), .Q (n_225));
  HS65_GS_SDFPQX9 retime_s2_11_reg(.CP (clk), .D (n_46), .TI (n_224),
       .TE (n_0), .Q (n_224));
  HS65_GS_SDFPQX9 retime_s2_14_reg(.CP (clk), .D (n_47), .TI (n_60),
       .TE (n_0), .Q (n_60));
  HS65_GS_FA1X4 g5775__1840(.A0 (n_284), .B0 (n_32), .CI (n_41), .CO
       (n_50), .S0 (n_51));
  HS65_GS_FA1X4 g5777__5019(.A0 (n_29), .B0 (n_42), .CI (n_38), .CO
       (n_48), .S0 (n_49));
  HS65_GS_PAOI2X1 g5778__1857(.A (n_45), .B (n_23), .P (n_25), .Z
       (n_47));
  HS65_GSS_XOR2X3 g5779__9906(.A (n_23), .B (n_45), .Z (n_46));
  HS65_GS_IVX7 g5780(.A (n_43), .Z (n_44));
  HS65_GS_FA1X4 g5781__8780(.A0 (n_19), .B0 (n_283), .CI (n_37), .CO
       (n_43), .S0 (n_45));
  HS65_GS_FA1X4 g5782__4296(.A0 (n_31), .B0 (n_2), .CI (n_33), .CO
       (n_41), .S0 (n_42));
  HS65_GS_FA1X4 g5785__3772(.A0 (n_12), .B0 (n_9), .CI (n_26), .CO
       (n_39), .S0 (n_40));
  HS65_GS_PAOI2X1 g5786__1474(.A (n_35), .B (n_21), .P (n_22), .Z
       (n_38));
  HS65_GSS_XNOR2X6 g5787__4547(.A (n_34), .B (n_28), .Z (n_37));
  HS65_GS_IVX9 g5789(.A (n_34), .Z (n_35));
  HS65_GS_FA1X4 g5790__2683(.A0 (n_3), .B0 (n_6), .CI (n_10), .CO
       (n_32), .S0 (n_33));
  HS65_GS_FA1X4 g5791__1309(.A0 (n_4), .B0 (n_1), .CI (n_5), .CO
       (n_31), .S0 (n_34));
  HS65_GS_OAI12X3 g5794__2900(.A (n_18), .B (n_24), .C (n_17), .Z
       (n_29));
  HS65_GSS_XOR2X6 g5795__2391(.A (n_21), .B (n_22), .Z (n_28));
  HS65_GS_AO22X9 g5798__7118(.A (n_7), .B (n_16), .C (n_13), .D (n_15),
       .Z (n_26));
  HS65_GS_PAOI2X6 g5811__1786(.A (n_255), .B (n_205), .P (n_254), .Z
       (n_25));
  HS65_GS_PAOI2X1 g5813__5953(.A (n_202), .B (n_210), .P (n_200), .Z
       (n_24));
  HS65_GS_PAOI2X1 g5814__5703(.A (n_209), .B (n_259), .P (n_207), .Z
       (n_19));
  HS65_GS_PAOI2X1 g5815__7114(.A (n_257), .B (n_256), .P (n_206), .Z
       (n_23));
  HS65_GS_PAOI2X6 g5816__5266(.A (n_262), .B (n_260), .P (n_208), .Z
       (n_22));
  HS65_GS_PAOI2X1 g5818__2250(.A (n_201), .B (n_263), .P (n_204), .Z
       (n_21));
  HS65_GS_NOR2X5 g5822__6083(.A (n_7), .B (n_203), .Z (n_18));
  HS65_GS_NAND2X7 g5823__2703(.A (n_8), .B (n_14), .Z (n_17));
  HS65_GS_OR2X9 g5824__5795(.A (n_12), .B (n_6), .Z (n_16));
  HS65_GS_NAND2X7 g5825__7344(.A (n_212), .B (n_235), .Z (n_11));
  HS65_GS_NAND2X7 g5826__1840(.A (n_216), .B (n_214), .Z (n_15));
  HS65_GS_NAND2X7 g5827__5019(.A (n_59), .B (n_235), .Z (n_10));
  HS65_GS_NAND2X7 g5828__1857(.A (n_273), .B (n_235), .Z (n_14));
  HS65_GS_NAND2X7 g5829__9906(.A (n_213), .B (n_212), .Z (n_13));
  HS65_GS_NAND2X7 g5830__8780(.A (n_214), .B (n_235), .Z (n_9));
  HS65_GS_NAND2X7 g5831__4296(.A (n_216), .B (n_212), .Z (n_12));
  HS65_GS_NAND2X7 g5832__3772(.A (n_218), .B (n_212), .Z (n_5));
  HS65_GS_NAND2X7 g5833__1474(.A (n_213), .B (n_211), .Z (n_8));
  HS65_GS_NAND2X7 g5834__4547(.A (n_59), .B (n_216), .Z (n_4));
  HS65_GS_NAND2X7 g5835__9682(.A (n_215), .B (n_212), .Z (n_3));
  HS65_GS_NAND2X7 g5836__2683(.A (n_211), .B (n_216), .Z (n_2));
  HS65_GS_NAND2X7 g5837__1309(.A (n_211), .B (n_235), .Z (n_7));
  HS65_GS_NAND2X7 g5838__6877(.A (n_215), .B (n_214), .Z (n_1));
  HS65_GS_NAND2X7 g5839__2900(.A (n_213), .B (n_214), .Z (n_6));
  HS65_GS_IVX9 g5840(.A (Q), .Z (n_0));
  HS65_GSS_XOR3X2 g2(.A (n_185), .B (n_179), .C (n_194), .Z (Z[7]));
  HS65_GSS_XOR3X2 g7194(.A (n_147), .B (n_139), .C (n_103), .Z (n_282));
  HS65_GSS_XOR3X2 g7195(.A (n_14), .B (n_24), .C (n_8), .Z (n_283));
  HS65_GSS_XOR3X2 g7196(.A (n_13), .B (n_7), .C (n_15), .Z (n_284));
  HS65_GSS_XNOR3X2 g7198(.A (n_164), .B (n_130), .C (n_160), .Z (Z[4]));
  HS65_GS_CB4I1X18 g7199(.A (n_185), .B (n_294), .C (n_194), .D
       (n_187), .Z (n_287));
  HS65_GSS_XNOR3X2 g7201(.A (n_144), .B (n_106), .C (n_137), .Z (Z[3]));
  HS65_GS_OA12X9 g7202(.A (n_79), .B (n_76), .C (n_107), .Z (n_290));
  HS65_GSS_XNOR3X2 g7204(.A (n_293), .B (n_162), .C (n_191), .Z (Z[6]));
  HS65_GSS1_FA1X9 g7205(.A0 (n_136), .B0 (n_143), .CI (n_172), .CO
       (n_294), .S0 (n_293));
  HS65_GS_IVX2 g3(.A (n_295), .Z (Z[11]));
  HS65_GS_FA1X4 g7206(.A0 (n_60), .B0 (n_229), .CI (n_225), .CO
       (n_297), .S0 (n_295));
  HS65_GS_XOR3X9 g7207(.A (n_131), .B (n_141), .C (n_154), .Z (n_298));
endmodule

module mac4(a, b, en, clk, reset, out);
  input [7:0] a, b;
  input en, clk, reset;
  output [15:0] out;
  wire [7:0] a, b;
  wire en, clk, reset;
  wire [15:0] out;
  wire [15:0] prod;
  wire [1:0] reg_en;
  wire n_0, n_1, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_33;
  wire n_70, n_98, n_99, n_100, n_101, n_102, \out[0]_171 , \out[1]_172
       ;
  wire \out[2]_173 , \out[3]_174 , \out[4]_175 , \out[5]_176 ,
       \out[6]_177 , \out[7]_178 , \out[8]_179 , \out[9]_180 ;
  wire \out[10]_181 , \out[11]_182 , \out[12]_183 , \out[13]_184 ,
       \out[14]_185 ;
  add_unsigned add_38_21(.A ({out[15:7], n_33, out[5], n_70, n_99,
       n_101, n_100, n_98}), .B (prod), .Z ({out[15], \out[14]_185 ,
       \out[13]_184 , \out[12]_183 , \out[11]_182 , \out[10]_181 ,
       \out[9]_180 , \out[8]_179 , \out[7]_178 , \out[6]_177 ,
       \out[5]_176 , \out[4]_175 , \out[3]_174 , \out[2]_173 ,
       \out[1]_172 , \out[0]_171 }), .clk (clk), .Q (reg_en[1]), .reset
       (reset), .Q_1 (reg_en[0]));
  mult_unsigned mul_31_23(.A (a), .B (b), .Z (prod), .clk (clk), .en
       (en), .Q (reg_en[0]));
  HS65_GS_BFX35 g129(.A (n_33), .Z (out[6]));
  HS65_GS_BFX35 g134(.A (n_98), .Z (out[0]));
  HS65_GS_BFX35 g132(.A (n_101), .Z (out[2]));
  HS65_GS_BFX35 g131(.A (n_100), .Z (out[1]));
  HS65_GS_BFX35 g127(.A (n_70), .Z (out[4]));
  HS65_GS_BFX35 g133(.A (n_99), .Z (out[3]));
  HS65_GS_DFPRQX9 \reg_en_reg[1] (.RN (reset), .CP (clk), .D
       (reg_en[0]), .Q (reg_en[1]));
  HS65_GS_DFPRQX4 \reg_en_reg[0] (.RN (reset), .CP (clk), .D (en), .Q
       (reg_en[0]));
  HS65_GS_DFPRQNX9 retime_s3_5_reg(.RN (reset), .CP (clk), .D (n_11),
       .QN (n_25));
  HS65_GS_DFPRQNX9 retime_s3_10_reg(.RN (reset), .CP (clk), .D (n_9),
       .QN (n_20));
  HS65_GS_DFPRQNX9 retime_s3_11_reg(.RN (reset), .CP (clk), .D (n_15),
       .QN (n_16));
  HS65_GS_SDFPRQX9 retime_s3_12_reg(.RN (reset), .CP (clk), .D (n_101),
       .TI (\out[2]_173 ), .TE (reg_en[1]), .Q (n_101));
  HS65_GS_DFPRQNX9 retime_s3_13_reg(.RN (reset), .CP (clk), .D (n_13),
       .QN (n_18));
  HS65_GS_DFPRQNX9 retime_s3_6_reg(.RN (reset), .CP (clk), .D (n_7),
       .QN (n_24));
  HS65_GSS_DFPRQNX18 retime_s3_15_reg(.RN (reset), .CP (clk), .D
       (n_10), .QN (n_19));
  HS65_GS_SDFPRQX9 retime_s3_16_reg(.RN (reset), .CP (clk), .D (n_33),
       .TI (\out[6]_177 ), .TE (reg_en[1]), .Q (n_33));
  HS65_GS_DFPRQX9 retime_s3_17_reg(.RN (reset), .CP (clk), .D (n_8), .Q
       (n_98));
  HS65_GS_DFPRQNX9 retime_s3_14_reg(.RN (reset), .CP (clk), .D (n_12),
       .QN (n_17));
  HS65_GS_DFPRQNX9 retime_s3_7_reg(.RN (reset), .CP (clk), .D (n_6),
       .QN (n_23));
  HS65_GS_DFPRQNX9 retime_s3_8_reg(.RN (reset), .CP (clk), .D (n_5),
       .QN (n_22));
  HS65_GS_DFPRQNX9 retime_s3_9_reg(.RN (reset), .CP (clk), .D (n_4),
       .QN (n_21));
  HS65_GS_MUX21I1X6 g142__2391(.D0 (n_16), .D1 (\out[1]_172 ), .S0
       (reg_en[1]), .Z (n_15));
  HS65_GS_MUX21I1X6 g144__7118(.D0 (n_18), .D1 (\out[4]_175 ), .S0
       (reg_en[1]), .Z (n_13));
  HS65_GS_MUX21I1X6 g145__8757(.D0 (n_17), .D1 (\out[3]_174 ), .S0
       (reg_en[1]), .Z (n_12));
  HS65_GS_MUX21I1X6 g146__1786(.D0 (n_25), .D1 (\out[12]_183 ), .S0
       (reg_en[1]), .Z (n_11));
  HS65_GS_MUX21I1X6 g147__5953(.D0 (n_19), .D1 (\out[5]_176 ), .S0
       (reg_en[1]), .Z (n_10));
  HS65_GS_MUX21I1X6 g148__5703(.D0 (n_20), .D1 (\out[7]_178 ), .S0
       (reg_en[1]), .Z (n_9));
  HS65_GS_MUX21X4 g149__7114(.D0 (n_98), .D1 (\out[0]_171 ), .S0
       (reg_en[1]), .Z (n_8));
  HS65_GS_MUX21I1X6 g150__5266(.D0 (n_24), .D1 (\out[11]_182 ), .S0
       (reg_en[1]), .Z (n_7));
  HS65_GS_MUX21I1X6 g151__2250(.D0 (n_23), .D1 (\out[10]_181 ), .S0
       (reg_en[1]), .Z (n_6));
  HS65_GS_MUX21I1X6 g152__6083(.D0 (n_22), .D1 (\out[9]_180 ), .S0
       (reg_en[1]), .Z (n_5));
  HS65_GS_MUX21I1X6 g153__2703(.D0 (n_21), .D1 (\out[8]_179 ), .S0
       (reg_en[1]), .Z (n_4));
  HS65_GS_IVX35 g159(.A (n_21), .Z (out[8]));
  HS65_GS_IVX35 g160(.A (n_24), .Z (out[11]));
  HS65_GS_IVX35 g161(.A (n_22), .Z (out[9]));
  HS65_GS_IVX35 g162(.A (n_25), .Z (out[12]));
  HS65_GS_IVX35 g163(.A (n_23), .Z (out[10]));
  HS65_GS_IVX44 g164(.A (n_20), .Z (out[7]));
  HS65_GS_IVX9 g166(.A (n_17), .Z (n_99));
  HS65_GS_IVX9 g167(.A (n_18), .Z (n_70));
  HS65_GS_IVX53 g168(.A (n_19), .Z (out[5]));
  HS65_GS_IVX18 g170(.A (n_16), .Z (n_100));
  HS65_GS_IVX7 g171(.A (reg_en[1]), .Z (n_1));
  HS65_GS_AO22X9 g2__1840(.A (n_1), .B (out[14]), .C (reg_en[1]), .D
       (\out[14]_185 ), .Z (n_0));
  HS65_GSS_DFPRQX35 retime_s3_4_reg(.RN (reset), .CP (clk), .D (n_102),
       .Q (out[13]));
  HS65_GSS_DFPRQX35 retime_s3_3_reg(.RN (reset), .CP (clk), .D (n_0),
       .Q (out[14]));
  HS65_GS_AO22X9 g2(.A (n_1), .B (out[13]), .C (reg_en[1]), .D
       (\out[13]_184 ), .Z (n_102));
endmodule

