
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Dec  9 2019 12:47:53 -02 (Dec  9 2019 14:47:53 UTC)

// Verification Directory fv/mac4 

module RC_CG_MOD_AUTO_mac4(ck_in, enable, test, ck_out);
  input ck_in, enable, test;
  output ck_out;
  wire ck_in, enable, test;
  wire ck_out;
  wire enl, n_0;
  HS65_GS_LDLQX9 enl_reg(.GN (ck_in), .D (n_0), .Q (enl));
  HS65_GS_OR2X9 g11__8780(.A (test), .B (enable), .Z (n_0));
  HS65_GS_AND2X4 g17__4296(.A (ck_in), .B (enl), .Z (ck_out));
endmodule

module add_unsigned(A, B, Z, clk, Q, reset, Q_1, RC_CG_GCLK_PORT);
  input [15:0] A, B;
  input clk, Q, reset, Q_1, RC_CG_GCLK_PORT;
  output [15:0] Z;
  wire [15:0] A, B;
  wire clk, Q, reset, Q_1, RC_CG_GCLK_PORT;
  wire [15:0] Z;
  wire UNCONNECTED, n_1, n_2, n_3, n_4, n_5, n_12, n_13;
  wire n_14, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_37, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_71, n_72, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_86;
  wire n_87, n_128, n_143;
  HS65_GS_DFPQX4 retime_s2_7_reg(.CP (RC_CG_GCLK_PORT), .D (B[9]), .Q
       (n_84));
  HS65_GS_DFPQX4 retime_s2_12_reg(.CP (RC_CG_GCLK_PORT), .D (B[8]), .Q
       (n_83));
  HS65_GS_DFPQX9 retime_s2_13_reg(.CP (RC_CG_GCLK_PORT), .D (B[7]), .Q
       (n_82));
  HS65_GS_DFPQX9 retime_s2_15_reg(.CP (RC_CG_GCLK_PORT), .D (B[1]), .Q
       (n_81));
  HS65_GS_DFPQX9 retime_s2_16_reg(.CP (RC_CG_GCLK_PORT), .D (B[2]), .Q
       (n_80));
  HS65_GS_DFPQX9 retime_s2_17_reg(.CP (RC_CG_GCLK_PORT), .D (B[6]), .Q
       (n_79));
  HS65_GS_DFPQX9 retime_s2_18_reg(.CP (RC_CG_GCLK_PORT), .D (B[4]), .Q
       (n_78));
  HS65_GS_DFPQX9 retime_s2_19_reg(.CP (RC_CG_GCLK_PORT), .D (B[0]), .Q
       (n_77));
  HS65_GS_DFPQX9 retime_s2_20_reg(.CP (RC_CG_GCLK_PORT), .D (B[3]), .Q
       (n_76));
  HS65_GS_DFPQX9 retime_s2_21_reg(.CP (RC_CG_GCLK_PORT), .D (B[5]), .Q
       (n_75));
  HS65_GSS_XNOR2X6 g2748__4547(.A (n_26), .B (n_128), .Z (Z[14]));
  HS65_GS_OAI21X6 g2749__9682(.A (n_21), .B (n_74), .C (n_17), .Z
       (n_128));
  HS65_GSS_XNOR2X6 g2750__2683(.A (n_25), .B (n_74), .Z (Z[13]));
  HS65_GS_OAI21X12 g2751__1309(.A (n_23), .B (n_72), .C (n_20), .Z
       (n_74));
  HS65_GS_AOI12X12 g2754__2900(.A (n_22), .B (n_71), .C (n_18), .Z
       (n_72));
  HS65_GSS_XNOR2X6 g2755__2391(.A (n_28), .B (n_71), .Z (Z[11]));
  HS65_GS_OAI12X12 g2756__7675(.A (n_24), .B (n_69), .C (n_19), .Z
       (n_71));
  HS65_GS_AOI12X12 g2759__8757(.A (n_40), .B (n_68), .C (n_41), .Z
       (n_69));
  HS65_GSS_XNOR2X6 g2760__1786(.A (n_52), .B (n_68), .Z (Z[9]));
  HS65_GS_NAND2X14 g2761__5953(.A (n_31), .B (n_67), .Z (n_68));
  HS65_GSS_XNOR2X6 g2762__5703(.A (n_50), .B (n_66), .Z (Z[8]));
  HS65_GS_NAND2AX7 g2763__7114(.A (n_46), .B (n_66), .Z (n_67));
  HS65_GS_NAND2X14 g2764__5266(.A (n_35), .B (n_65), .Z (n_66));
  HS65_GSS_XNOR2X6 g2765__2250(.A (n_49), .B (n_64), .Z (Z[7]));
  HS65_GS_NAND2AX14 g2766__6083(.A (n_45), .B (n_64), .Z (n_65));
  HS65_GS_OAI12X9 g2767__2703(.A (n_37), .B (n_63), .C (n_30), .Z
       (n_64));
  HS65_GS_OAI12X9 g2770__5795(.A (n_34), .B (n_62), .C (n_42), .Z
       (n_63));
  HS65_GSS_XNOR2X6 g2771__7344(.A (n_54), .B (n_62), .Z (Z[5]));
  HS65_GS_NAND2X14 g2772__1840(.A (n_33), .B (n_61), .Z (n_62));
  HS65_GSS_XNOR2X6 g2773__5019(.A (n_53), .B (n_60), .Z (Z[4]));
  HS65_GS_NAND2AX7 g2774__1857(.A (n_43), .B (n_60), .Z (n_61));
  HS65_GS_NAND2X14 g2775__9906(.A (n_32), .B (n_59), .Z (n_60));
  HS65_GSS_XNOR2X6 g2776__8780(.A (n_51), .B (n_143), .Z (Z[3]));
  HS65_GS_NAND2AX7 g2777__4296(.A (n_44), .B (n_143), .Z (n_59));
  HS65_GSS_XOR3X2 g2778__3772(.A (A[2]), .B (n_80), .C (n_56), .Z
       (Z[2]));
  HS65_GS_OAI21X3 g2781__9682(.A (n_47), .B (n_14), .C (n_39), .Z
       (n_56));
  HS65_GSS_XNOR2X6 g2782__2683(.A (n_14), .B (n_55), .Z (Z[1]));
  HS65_GS_NOR2AX3 g2783__1309(.A (n_39), .B (n_47), .Z (n_55));
  HS65_GS_NAND2AX7 g2784__6877(.A (n_34), .B (n_42), .Z (n_54));
  HS65_GS_NAND2AX7 g2785__2900(.A (n_43), .B (n_33), .Z (n_53));
  HS65_GS_NAND2AX7 g2786__2391(.A (n_41), .B (n_40), .Z (n_52));
  HS65_GS_OA12X9 g2787__7675(.A (n_77), .B (A[0]), .C (n_14), .Z
       (Z[0]));
  HS65_GS_NAND2AX7 g2788__7118(.A (n_44), .B (n_32), .Z (n_51));
  HS65_GS_NAND2AX7 g2789__8757(.A (n_46), .B (n_31), .Z (n_50));
  HS65_GS_NAND2AX7 g2790__1786(.A (n_45), .B (n_35), .Z (n_49));
  HS65_GSS_XOR2X6 g2791__5953(.A (n_79), .B (A[6]), .Z (n_48));
  HS65_GS_NOR2X6 g2793__7114(.A (n_79), .B (A[6]), .Z (n_37));
  HS65_GS_NOR2X6 g2795__2250(.A (n_81), .B (A[1]), .Z (n_47));
  HS65_GS_NOR2X5 g2796__6083(.A (A[8]), .B (n_83), .Z (n_46));
  HS65_GS_NOR2X6 g2797__2703(.A (n_82), .B (A[7]), .Z (n_45));
  HS65_GS_NOR2X6 g2798__5795(.A (n_76), .B (A[3]), .Z (n_44));
  HS65_GS_NOR2X6 g2799__7344(.A (n_78), .B (A[4]), .Z (n_43));
  HS65_GS_OR2X9 g2800__1840(.A (n_75), .B (A[5]), .Z (n_42));
  HS65_GS_AND2X4 g2801__5019(.A (A[9]), .B (n_84), .Z (n_41));
  HS65_GS_OR2X9 g2802__1857(.A (n_84), .B (A[9]), .Z (n_40));
  HS65_GS_NAND2X7 g2803__9906(.A (n_81), .B (A[1]), .Z (n_39));
  HS65_GS_NAND2X7 g2805__8780(.A (n_79), .B (A[6]), .Z (n_30));
  HS65_GS_OR2ABX18 g2807__3772(.A (n_82), .B (A[7]), .Z (n_35));
  HS65_GS_NAND2AX7 g2808__1474(.A (n_23), .B (n_20), .Z (n_29));
  HS65_GS_NAND2AX7 g2809__4547(.A (n_18), .B (n_22), .Z (n_28));
  HS65_GS_NAND2AX7 g2810__9682(.A (n_24), .B (n_19), .Z (n_27));
  HS65_GS_AND2X4 g2811__2683(.A (A[5]), .B (n_75), .Z (n_34));
  HS65_GS_NAND2X7 g2812__1309(.A (n_78), .B (A[4]), .Z (n_33));
  HS65_GS_NAND2X7 g2813__6877(.A (n_76), .B (A[3]), .Z (n_32));
  HS65_GSS_XOR2X6 g2814__2900(.A (A[14]), .B (B[14]), .Z (n_26));
  HS65_GS_NAND2X5 g2815__2391(.A (n_83), .B (A[8]), .Z (n_31));
  HS65_GS_NAND2AX7 g2816__7675(.A (n_21), .B (n_17), .Z (n_25));
  HS65_GS_NAND2X7 g2817__7118(.A (n_77), .B (A[0]), .Z (n_14));
  HS65_GS_NOR2X6 g2830__5953(.A (B[10]), .B (n_13), .Z (n_24));
  HS65_GS_NOR2X6 g2831__5703(.A (n_12), .B (B[12]), .Z (n_23));
  HS65_GS_OR2X9 g2832__7114(.A (B[11]), .B (A[11]), .Z (n_22));
  HS65_GS_AND2X4 g2833__5266(.A (B[13]), .B (A[13]), .Z (n_21));
  HS65_GS_NAND2X7 g2834__2250(.A (n_12), .B (B[12]), .Z (n_20));
  HS65_GS_NAND2X7 g2835__6083(.A (B[10]), .B (n_13), .Z (n_19));
  HS65_GS_AND2X4 g2836__2703(.A (A[11]), .B (B[11]), .Z (n_18));
  HS65_GS_OR2X9 g2837__5795(.A (A[13]), .B (B[13]), .Z (n_17));
  HS65_GS_BFX7 drc_bufs2871(.A (A[10]), .Z (n_13));
  HS65_GS_BFX7 drc_bufs2873(.A (A[12]), .Z (n_12));
  HS65_GSS_XNOR2X6 g2__7344(.A (n_63), .B (n_48), .Z (Z[6]));
  HS65_GS_SDFPSQTX9 retime_s3_2_reg(.SN (reset), .CP (clk), .D (n_5),
       .TI (n_86), .TE (n_1), .Q (n_86), .TQ (UNCONNECTED));
  HS65_GS_SDFPRQX9 retime_s3_1_reg(.RN (reset), .CP (clk), .D (n_4),
       .TI (n_87), .TE (n_1), .Q (n_87));
  HS65_GS_OAI12X6 g1954__1840(.A (n_3), .B (n_128), .C (n_2), .Z (n_5));
  HS65_GSS_XNOR2X6 g1955__5019(.A (A[15]), .B (B[15]), .Z (n_4));
  HS65_GS_NOR2X6 g1956__1857(.A (A[14]), .B (B[14]), .Z (n_3));
  HS65_GS_NAND2X7 g1957__9906(.A (A[14]), .B (B[14]), .Z (n_2));
  HS65_GS_IVX7 g1958(.A (Q), .Z (n_1));
  HS65_GS_XOR2X4 g2(.A (n_72), .B (n_29), .Z (Z[12]));
  HS65_GS_XOR2X4 g2893(.A (n_69), .B (n_27), .Z (Z[10]));
  HS65_GS_PAO2X9 g2894(.A (n_80), .B (A[2]), .P (n_56), .Z (n_143));
  HS65_GS_XNOR2X35 g2895(.A (n_87), .B (n_86), .Z (Z[15]));
endmodule

module RC_CG_MOD_AUTO_mac4_2(ck_in, enable, test, ck_out);
  input ck_in, enable, test;
  output ck_out;
  wire ck_in, enable, test;
  wire ck_out;
  wire enl, n_0;
  HS65_GS_LDLQX9 enl_reg(.GN (ck_in), .D (n_0), .Q (enl));
  HS65_GS_OR2X9 g11__8780(.A (test), .B (enable), .Z (n_0));
  HS65_GS_AND2X4 g17__4296(.A (ck_in), .B (enl), .Z (ck_out));
endmodule

module mult_unsigned(A, B, Z, clk, en, Q, RC_CG_GCLK_PORT);
  input [7:0] A, B;
  input clk, en, Q, RC_CG_GCLK_PORT;
  output [15:0] Z;
  wire [7:0] A, B;
  wire clk, en, Q, RC_CG_GCLK_PORT;
  wire [15:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_97, n_98, n_99, n_100;
  wire n_102, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_112, n_114, n_116, n_117, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_142, n_143, n_144, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_220, n_221, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_281, n_282, n_283, n_284, n_288, n_289;
  wire n_290, rc_gclk;
  RC_CG_MOD_AUTO_mac4_2 RC_CG_HIER_INST3(.ck_in (clk), .enable (en),
       .test (1'b0), .ck_out (rc_gclk));
  HS65_GS_DFPQX9 retime_s1_1_reg(.CP (rc_gclk), .D (B[7]), .Q (n_243));
  HS65_GSS_DFPQNX18 retime_s1_2_reg(.CP (rc_gclk), .D (A[0]), .QN
       (n_231));
  HS65_GSS_DFPQNX18 retime_s1_3_reg(.CP (rc_gclk), .D (A[2]), .QN
       (n_230));
  HS65_GSS_DFPQNX18 retime_s1_4_reg(.CP (rc_gclk), .D (B[0]), .QN
       (n_229));
  HS65_GS_DFPQX9 retime_s1_5_reg(.CP (rc_gclk), .D (A[1]), .Q (n_5));
  HS65_GSS_DFPQNX18 retime_s1_6_reg(.CP (rc_gclk), .D (B[2]), .QN
       (n_228));
  HS65_GS_DFPQX9 retime_s1_7_reg(.CP (rc_gclk), .D (B[3]), .Q (n_227));
  HS65_GSS_DFPQNX18 retime_s1_8_reg(.CP (rc_gclk), .D (B[1]), .QN
       (n_226));
  HS65_GS_DFPQX9 retime_s1_9_reg(.CP (rc_gclk), .D (B[6]), .Q (n_225));
  HS65_GSS_DFPQNX18 retime_s1_10_reg(.CP (rc_gclk), .D (B[4]), .QN
       (n_224));
  HS65_GSS_DFPQNX18 retime_s1_11_reg(.CP (rc_gclk), .D (A[6]), .QN
       (n_223));
  HS65_GSS_DFPQNX18 retime_s1_13_reg(.CP (rc_gclk), .D (A[7]), .QN
       (n_221));
  HS65_GSS_DFPQNX18 retime_s1_14_reg(.CP (rc_gclk), .D (A[3]), .QN
       (n_218));
  HS65_GS_DFPQX9 retime_s1_15_reg(.CP (rc_gclk), .D (A[4]), .Q (n_217));
  HS65_GS_DFPQX9 retime_s1_16_reg(.CP (rc_gclk), .D (A[5]), .Q (n_220));
  HS65_GS_DFPQX9 retime_s2_1_reg(.CP (RC_CG_GCLK_PORT), .D (n_148), .Q
       (n_242));
  HS65_GS_DFPQX9 retime_s2_2_reg(.CP (RC_CG_GCLK_PORT), .D (n_149), .Q
       (n_241));
  HS65_GS_DFPQX9 retime_s2_3_reg(.CP (RC_CG_GCLK_PORT), .D (n_180), .Q
       (n_240));
  HS65_GS_DFPQX9 retime_s2_4_reg(.CP (RC_CG_GCLK_PORT), .D (n_181), .Q
       (n_239));
  HS65_GS_DFPQX9 retime_s2_5_reg(.CP (RC_CG_GCLK_PORT), .D (n_193), .Q
       (n_238));
  HS65_GS_DFPQX4 retime_s2_6_reg(.CP (RC_CG_GCLK_PORT), .D (n_205), .Q
       (n_237));
  HS65_GS_DFPQX9 retime_s2_8_reg(.CP (RC_CG_GCLK_PORT), .D (n_23), .Q
       (n_236));
  HS65_GS_DFPQX9 retime_s2_9_reg(.CP (RC_CG_GCLK_PORT), .D (n_194), .Q
       (n_235));
  HS65_GS_DFPQX9 retime_s2_10_reg(.CP (RC_CG_GCLK_PORT), .D (n_195), .Q
       (n_234));
  HS65_GS_DFPQX4 retime_s2_11_reg(.CP (RC_CG_GCLK_PORT), .D (n_197), .Q
       (n_233));
  HS65_GS_DFPQX9 retime_s2_14_reg(.CP (RC_CG_GCLK_PORT), .D (n_206), .Q
       (n_232));
  HS65_GS_IVX9 g7757(.A (n_216), .Z (Z[14]));
  HS65_GS_IVX9 g7758(.A (n_215), .Z (Z[15]));
  HS65_GS_FA1X4 g7759__4547(.A0 (n_242), .B0 (n_236), .CI (n_214), .CO
       (n_215), .S0 (n_216));
  HS65_GSS_XNOR2X6 g7760__9682(.A (n_241), .B (n_213), .Z (Z[13]));
  HS65_GS_AOI21X2 g7761__2683(.A (n_152), .B (n_211), .C (n_212), .Z
       (n_214));
  HS65_GS_NOR2AX3 g7762__1309(.A (n_211), .B (n_212), .Z (n_213));
  HS65_GS_NOR2X6 g7763__6877(.A (n_240), .B (n_210), .Z (n_212));
  HS65_GS_NAND2X7 g7764__2900(.A (n_240), .B (n_210), .Z (n_211));
  HS65_GS_IVX9 g7765(.A (n_209), .Z (Z[12]));
  HS65_GS_FA1X4 g7766__2391(.A0 (n_235), .B0 (n_239), .CI (n_207), .CO
       (n_210), .S0 (n_209));
  HS65_GS_IVX9 g7767(.A (n_208), .Z (Z[11]));
  HS65_GS_FA1X4 g7768__7675(.A0 (n_232), .B0 (n_234), .CI (n_238), .CO
       (n_207), .S0 (n_208));
  HS65_GSS_XOR2X6 g7770__7118(.A (n_237), .B (n_233), .Z (Z[10]));
  HS65_GS_PAO2X9 g7771__8757(.A (n_196), .B (n_192), .P (n_204), .Z
       (n_206));
  HS65_GS_IVX9 g7773(.A (n_203), .Z (Z[9]));
  HS65_GS_IVX4 g7774(.A (n_204), .Z (n_205));
  HS65_GS_FA1X4 g7775__1786(.A0 (n_191), .B0 (n_187), .CI (n_201), .CO
       (n_204), .S0 (n_203));
  HS65_GS_IVX9 g7776(.A (n_202), .Z (Z[8]));
  HS65_GS_FA1X4 g7777__5953(.A0 (n_188), .B0 (n_184), .CI (n_199), .CO
       (n_201), .S0 (n_202));
  HS65_GS_PAO2X9 g7780__7114(.A (n_185), .B (n_172), .P (n_198), .Z
       (n_199));
  HS65_GSS_XOR3X2 g7781__5266(.A (n_171), .B (n_169), .C (n_189), .Z
       (Z[6]));
  HS65_GS_OAI12X5 g7783__2250(.A (n_177), .B (n_189), .C (n_176), .Z
       (n_198));
  HS65_GSS_XOR2X6 g7784__6083(.A (n_192), .B (n_196), .Z (n_197));
  HS65_GS_FA1X4 g7788__2703(.A0 (n_163), .B0 (n_146), .CI (n_182), .CO
       (n_194), .S0 (n_195));
  HS65_GS_FA1X4 g7789__5795(.A0 (n_183), .B0 (n_281), .CI (n_178), .CO
       (n_193), .S0 (n_196));
  HS65_GS_FA1X4 g7791__1840(.A0 (n_174), .B0 (n_151), .CI (n_179), .CO
       (n_192), .S0 (n_191));
  HS65_GSS_XOR2X6 g7792__5019(.A (n_172), .B (n_185), .Z (n_190));
  HS65_GS_PAOI2X6 g7793__1857(.A (n_158), .B (n_170), .P (n_173), .Z
       (n_189));
  HS65_GS_FA1X4 g7794__9906(.A0 (n_150), .B0 (n_164), .CI (n_175), .CO
       (n_187), .S0 (n_188));
  HS65_GSS1_FA1X9 g7796__8780(.A0 (n_161), .B0 (n_156), .CI (n_165),
       .CO (n_184), .S0 (n_185));
  HS65_GS_FA1X4 g7799__4296(.A0 (n_123), .B0 (n_126), .CI (n_166), .CO
       (n_182), .S0 (n_183));
  HS65_GS_FA1X4 g7800__3772(.A0 (n_283), .B0 (n_128), .CI (n_162), .CO
       (n_180), .S0 (n_181));
  HS65_GSS1_FA1X9 g7801__1474(.A0 (n_112), .B0 (n_138), .CI (n_167),
       .CO (n_178), .S0 (n_179));
  HS65_GS_NOR2X6 g7802__4547(.A (n_169), .B (n_171), .Z (n_177));
  HS65_GS_NAND2X7 g7803__9682(.A (n_169), .B (n_171), .Z (n_176));
  HS65_GSS_XOR3X2 g7804__2683(.A (n_159), .B (n_119), .C (n_160), .Z
       (Z[4]));
  HS65_GSS1_FA1X9 g7805__1309(.A0 (n_140), .B0 (n_124), .CI (n_155),
       .CO (n_174), .S0 (n_175));
  HS65_GS_PAOI2X6 g7806__6877(.A (n_119), .B (n_160), .P (n_159), .Z
       (n_173));
  HS65_GS_PAOI2X1 g7807__2900(.A (n_132), .B (n_135), .P (n_168), .Z
       (n_172));
  HS65_GS_MUX21I1X12 g7808__2391(.D0 (n_168), .D1 (n_168), .S0 (n_153),
       .Z (n_171));
  HS65_GSS1_FA1X9 g7809__7675(.A0 (n_117), .B0 (n_120), .CI (n_143),
       .CO (n_169), .S0 (n_170));
  HS65_GSS1_FA1X9 g7810__7118(.A0 (n_139), .B0 (n_6), .CI (n_127), .CO
       (n_166), .S0 (n_167));
  HS65_GSS1_FA1X9 g7811__8757(.A0 (n_288), .B0 (n_125), .CI (n_290),
       .CO (n_164), .S0 (n_165));
  HS65_GS_FA1X4 g7812__1786(.A0 (n_122), .B0 (n_20), .CI (n_129), .CO
       (n_162), .S0 (n_163));
  HS65_GS_PAO2X9 g7813__5953(.A (n_107), .B (n_133), .P (n_134), .Z
       (n_161));
  HS65_GS_XOR2X18 g7814__5703(.A (n_106), .B (n_144), .Z (n_168));
  HS65_GSS_XOR2X6 g7815__7114(.A (n_136), .B (n_147), .Z (Z[3]));
  HS65_GS_PAO2X18 g7816__5266(.A (n_90), .B (n_136), .P (n_131), .Z
       (n_160));
  HS65_GS_IVX9 g7817(.A (n_157), .Z (n_158));
  HS65_GS_FA1X9 g7818__2250(.A0 (n_130), .B0 (n_86), .CI (n_102), .CO
       (n_155), .S0 (n_156));
  HS65_GSS1_FA1X9 g7819__6083(.A0 (n_289), .B0 (n_87), .CI (n_116), .CO
       (n_157), .S0 (n_159));
  HS65_GS_XOR2X18 g7821__5795(.A (n_132), .B (n_135), .Z (n_153));
  HS65_GS_IVX7 g7822(.A (n_241), .Z (n_152));
  HS65_GS_PAOI2X1 g7825__7344(.A (n_89), .B (n_114), .P (n_282), .Z
       (n_151));
  HS65_GSS_XNOR2X6 g7826__1840(.A (n_137), .B (n_282), .Z (n_150));
  HS65_GS_FA1X4 g7827__5019(.A0 (n_60), .B0 (n_19), .CI (n_108), .CO
       (n_148), .S0 (n_149));
  HS65_GSS_XOR2X6 g7828__1857(.A (n_90), .B (n_131), .Z (n_147));
  HS65_GS_CB4I6X9 g7829__9906(.A (n_58), .B (n_36), .C (n_142), .D
       (n_82), .Z (n_146));
  HS65_GS_XOR2X18 g7831__4296(.A (n_133), .B (n_134), .Z (n_144));
  HS65_GS_XNOR2X18 g7832__3772(.A (n_98), .B (n_121), .Z (n_143));
  HS65_GS_FA1X4 g7833__1474(.A0 (n_22), .B0 (n_58), .CI (n_57), .CO
       (n_139), .S0 (n_140));
  HS65_GS_FA1X4 g7834__4547(.A0 (n_51), .B0 (n_47), .CI (n_56), .CO
       (n_142), .S0 (n_138));
  HS65_GSS_XOR2X6 g7835__9682(.A (n_89), .B (n_114), .Z (n_137));
  HS65_GS_PAO2X18 g7837__1309(.A (n_37), .B (n_91), .P (n_99), .Z
       (n_136));
  HS65_GS_PAO2X9 g7838__6877(.A (n_35), .B (n_110), .P (n_98), .Z
       (n_135));
  HS65_GSS1_FA1X9 g7839__2900(.A0 (n_15), .B0 (n_48), .CI (n_55), .CO
       (n_130), .S0 (n_134));
  HS65_GS_FA1X4 g7840__2391(.A0 (n_52), .B0 (n_24), .CI (n_53), .CO
       (n_128), .S0 (n_129));
  HS65_GS_FA1X4 g7841__7675(.A0 (n_62), .B0 (n_59), .CI (n_18), .CO
       (n_126), .S0 (n_127));
  HS65_GS_FA1X9 g7842__7118(.A0 (n_16), .B0 (n_49), .CI (n_54), .CO
       (n_124), .S0 (n_125));
  HS65_GS_FA1X4 g7843__8757(.A0 (n_17), .B0 (n_50), .CI (n_21), .CO
       (n_122), .S0 (n_123));
  HS65_GS_XNOR2X18 g7844__1786(.A (n_35), .B (n_92), .Z (n_121));
  HS65_GS_PAO2X18 g7845__5953(.A (n_25), .B (n_72), .P (n_34), .Z
       (n_133));
  HS65_GS_PAO2X9 g7846__5703(.A (n_39), .B (n_64), .P (n_40), .Z
       (n_120));
  HS65_GS_XOR2X18 g7847__7114(.A (n_2), .B (n_97), .Z (n_132));
  HS65_GS_XOR2X9 g7848__5266(.A (n_95), .B (n_100), .Z (n_131));
  HS65_GSS_XOR3X2 g7849__2250(.A (n_91), .B (n_37), .C (n_99), .Z
       (Z[2]));
  HS65_GS_XOR2X9 g7851__2703(.A (n_72), .B (n_94), .Z (n_117));
  HS65_GS_PAO2X9 g7852__5795(.A (n_1), .B (n_32), .P (n_100), .Z
       (n_119));
  HS65_GS_XNOR2X18 g7853__7344(.A (n_40), .B (n_93), .Z (n_116));
  HS65_GS_OA12X9 g7856__1857(.A (n_69), .B (n_0), .C (n_104), .Z
       (n_114));
  HS65_GS_PAO2X9 g7857__9906(.A (n_26), .B (n_67), .P (n_105), .Z
       (n_112));
  HS65_GS_IVX7 g7859(.A (n_92), .Z (n_110));
  HS65_GS_IVX4 g7860(.A (n_2), .Z (n_109));
  HS65_GS_AO22X9 g7861__4296(.A (n_36), .B (n_81), .C (n_74), .D
       (n_77), .Z (n_108));
  HS65_GS_IVX7 g7862(.A (n_106), .Z (n_107));
  HS65_GS_NOR2X5 g7863__3772(.A (n_79), .B (n_91), .Z (Z[1]));
  HS65_GS_OAI12X3 g7864__1474(.A (n_30), .B (n_40), .C (n_43), .Z
       (n_104));
  HS65_GS_NOR2X6 g7866__9682(.A (n_80), .B (n_85), .Z (n_106));
  HS65_GS_CBI4I1X5 g7867__2683(.A (n_227), .B (n_217), .C (n_46), .D
       (n_88), .Z (n_102));
  HS65_GS_NAND2X7 g7869__6877(.A (n_78), .B (n_6), .Z (n_105));
  HS65_GSS_XNOR2X6 g7870__2900(.A (n_28), .B (n_66), .Z (n_97));
  HS65_GS_MUX21I1X6 g7872__7675(.D0 (n_31), .D1 (n_31), .S0 (n_1), .Z
       (n_95));
  HS65_GS_MUX21I1X6 g7873__7118(.D0 (n_25), .D1 (n_25), .S0 (n_33), .Z
       (n_94));
  HS65_GSS_XNOR2X6 g7874__8757(.A (n_38), .B (n_64), .Z (n_93));
  HS65_GSS_XOR2X6 g7875__1786(.A (n_42), .B (n_73), .Z (n_100));
  HS65_GS_MUX21I1X6 g7876__5953(.D0 (n_70), .D1 (n_70), .S0 (n_63), .Z
       (n_99));
  HS65_GSS_XNOR2X6 g7877__5703(.A (n_41), .B (n_65), .Z (n_98));
  HS65_GS_IVX9 g7878(.A (n_88), .Z (n_89));
  HS65_GS_NAND2X7 g7882__7114(.A (n_76), .B (n_45), .Z (n_92));
  HS65_GS_NOR2AX6 g7883__5266(.A (Z[0]), .B (n_63), .Z (n_91));
  HS65_GS_NOR2X6 g7884__2250(.A (n_42), .B (n_73), .Z (n_87));
  HS65_GS_NOR2X6 g7885__6083(.A (n_71), .B (n_63), .Z (n_90));
  HS65_GS_OR2X9 g7886__2703(.A (n_59), .B (n_65), .Z (n_88));
  HS65_GS_NAND2X7 g7887__5795(.A (n_61), .B (n_46), .Z (n_6));
  HS65_GS_IVX9 g7888(.A (n_85), .Z (n_86));
  HS65_GS_AND2X4 g7891__5019(.A (n_68), .B (n_30), .Z (n_82));
  HS65_GS_OR2X9 g7892__1857(.A (n_60), .B (n_24), .Z (n_81));
  HS65_GS_AOI22X6 g7893__9906(.A (n_220), .B (n_13), .C (n_12), .D
       (n_227), .Z (n_80));
  HS65_GS_AOI22X4 g7894__8780(.A (n_5), .B (n_10), .C (n_4), .D (n_13),
       .Z (n_79));
  HS65_GS_OAI22X6 g7895__4296(.A (n_221), .B (n_226), .C (n_223), .D
       (n_228), .Z (n_78));
  HS65_GS_NOR2X6 g7896__3772(.A (n_75), .B (n_57), .Z (n_85));
  HS65_GS_IVX7 g7897(.A (n_76), .Z (n_75));
  HS65_GS_IVX4 g7898(.A (n_70), .Z (n_71));
  HS65_GS_IVX9 g7899(.A (n_61), .Z (n_62));
  HS65_GS_NAND2X7 g7900__1474(.A (n_9), .B (n_284), .Z (n_77));
  HS65_GS_AND2X18 g7901__4547(.A (n_13), .B (n_12), .Z (n_76));
  HS65_GS_NAND2X7 g7902__9682(.A (n_8), .B (n_225), .Z (n_74));
  HS65_GS_NAND2X7 g7903__2683(.A (n_11), .B (n_220), .Z (n_56));
  HS65_GS_NAND2X7 g7904__1309(.A (n_7), .B (n_5), .Z (n_73));
  HS65_GS_NAND2X7 g7905__6877(.A (n_284), .B (n_4), .Z (n_72));
  HS65_GS_NAND2X7 g7906__2900(.A (n_7), .B (n_217), .Z (n_55));
  HS65_GS_NOR2X6 g7907__2391(.A (n_231), .B (n_228), .Z (n_70));
  HS65_GS_NOR2X6 g7908__7675(.A (n_230), .B (n_14), .Z (n_69));
  HS65_GS_NAND2X7 g7909__7118(.A (n_243), .B (n_12), .Z (n_68));
  HS65_GS_NAND2X7 g7910__8757(.A (n_9), .B (n_10), .Z (n_54));
  HS65_GS_NAND2X5 g7911__1786(.A (n_243), .B (n_217), .Z (n_53));
  HS65_GS_NAND2X7 g7912__5953(.A (n_9), .B (n_11), .Z (n_52));
  HS65_GS_NAND2X7 g7913__5703(.A (n_225), .B (n_12), .Z (n_51));
  HS65_GS_NAND2X7 g7914__7114(.A (n_3), .B (n_225), .Z (n_67));
  HS65_GS_NAND2X7 g7915__5266(.A (n_225), .B (n_217), .Z (n_50));
  HS65_GS_NAND2X7 g7916__2250(.A (n_243), .B (n_4), .Z (n_49));
  HS65_GS_NAND2X7 g7917__6083(.A (n_8), .B (n_10), .Z (n_66));
  HS65_GS_NAND2X14 g7918__2703(.A (n_13), .B (n_217), .Z (n_65));
  HS65_GS_NAND2X7 g7919__5795(.A (n_10), .B (n_217), .Z (n_64));
  HS65_GS_NAND2X7 g7920__7344(.A (n_13), .B (n_5), .Z (n_63));
  HS65_GS_NOR2X6 g7921__1840(.A (n_221), .B (n_228), .Z (n_61));
  HS65_GS_NAND2AX14 g7922__5019(.A (n_230), .B (n_11), .Z (n_48));
  HS65_GS_NAND2X7 g7923__1857(.A (n_3), .B (n_243), .Z (n_47));
  HS65_GS_NAND2X7 g7924__9906(.A (n_9), .B (n_225), .Z (n_60));
  HS65_GS_NAND2X7 g7925__8780(.A (n_8), .B (n_227), .Z (n_59));
  HS65_GS_NAND2X7 g7926__4296(.A (n_284), .B (n_12), .Z (n_58));
  HS65_GS_NAND2X7 g7927__3772(.A (n_227), .B (n_220), .Z (n_57));
  HS65_GS_IVX7 g7930(.A (n_38), .Z (n_39));
  HS65_GS_IVX9 g7931(.A (n_33), .Z (n_34));
  HS65_GS_IVX7 g7932(.A (n_31), .Z (n_32));
  HS65_GS_IVX9 g7933(.A (n_28), .Z (n_29));
  HS65_GS_NAND2X5 g7935__1474(.A (n_9), .B (n_243), .Z (n_23));
  HS65_GS_NOR2X6 g7936__4547(.A (n_223), .B (n_226), .Z (n_46));
  HS65_GS_AND2X9 g7937__9682(.A (n_227), .B (n_5), .Z (n_45));
  HS65_GS_NOR2X6 g7938__2683(.A (n_231), .B (n_229), .Z (Z[0]));
  HS65_GS_NAND2X7 g7939__1309(.A (n_11), .B (n_12), .Z (n_43));
  HS65_GS_NAND2X5 g7941__6877(.A (n_217), .B (n_11), .Z (n_22));
  HS65_GS_NAND2X7 g7942__2900(.A (n_3), .B (n_13), .Z (n_42));
  HS65_GS_AND2X9 g7943__2391(.A (n_3), .B (n_227), .Z (n_41));
  HS65_GS_NAND2X5 g7944__7675(.A (n_9), .B (n_227), .Z (n_21));
  HS65_GS_NAND2X7 g7945__7118(.A (n_3), .B (n_7), .Z (n_40));
  HS65_GS_NOR2X6 g7946__8757(.A (n_231), .B (n_224), .Z (n_38));
  HS65_GS_NOR2X6 g7947__1786(.A (n_230), .B (n_229), .Z (n_37));
  HS65_GS_NAND2X7 g7948__5953(.A (n_225), .B (n_220), .Z (n_20));
  HS65_GS_NAND2X7 g7949__5703(.A (n_243), .B (n_220), .Z (n_36));
  HS65_GS_AND2X9 g7950__7114(.A (n_10), .B (n_220), .Z (n_35));
  HS65_GS_NAND2X7 g7951__5266(.A (n_8), .B (n_243), .Z (n_19));
  HS65_GS_AND2X18 g7952__2250(.A (n_11), .B (n_5), .Z (n_33));
  HS65_GS_NAND2X7 g7953__6083(.A (n_10), .B (n_12), .Z (n_31));
  HS65_GS_NAND2X5 g7954__2703(.A (n_217), .B (n_284), .Z (n_18));
  HS65_GS_NAND2X7 g7955__5795(.A (n_8), .B (n_11), .Z (n_17));
  HS65_GS_NAND2X7 g7956__7344(.A (n_284), .B (n_220), .Z (n_30));
  HS65_GS_NAND2X7 g7957__1840(.A (n_225), .B (n_5), .Z (n_16));
  HS65_GS_NAND2X7 g7959__5019(.A (n_284), .B (n_5), .Z (n_15));
  HS65_GS_AND2X9 g7960__1857(.A (n_225), .B (n_4), .Z (n_28));
  HS65_GS_NAND2X7 g7961__9906(.A (n_243), .B (n_5), .Z (n_26));
  HS65_GS_NAND2X7 g7962__8780(.A (n_7), .B (n_12), .Z (n_25));
  HS65_GS_NAND2X7 g7963__4296(.A (n_8), .B (n_284), .Z (n_24));
  HS65_GS_IVX7 g7964(.A (n_284), .Z (n_14));
  HS65_GS_IVX18 g7965(.A (n_226), .Z (n_13));
  HS65_GS_IVX18 g7966(.A (n_218), .Z (n_12));
  HS65_GS_IVX18 g7967(.A (n_224), .Z (n_11));
  HS65_GS_IVX18 g7985(.A (n_231), .Z (n_4));
  HS65_GS_IVX9 g7986(.A (n_229), .Z (n_10));
  HS65_GS_IVX9 g7993(.A (n_221), .Z (n_9));
  HS65_GS_IVX18 g7994(.A (n_223), .Z (n_8));
  HS65_GS_IVX18 g7995(.A (n_228), .Z (n_7));
  HS65_GS_IVX13 g7999(.A (n_230), .Z (n_3));
  HS65_GS_NOR2AX13 g2__3772(.A (n_41), .B (n_65), .Z (n_2));
  HS65_GS_NOR2AX13 g8009__1474(.A (n_227), .B (n_231), .Z (n_1));
  HS65_GS_NOR2AX6 g8010__4547(.A (n_220), .B (n_228), .Z (n_0));
  HS65_GSS_XOR3X2 g2(.A (n_68), .B (n_142), .C (n_30), .Z (n_281));
  HS65_GSS_XNOR3X4 g8011(.A (n_67), .B (n_105), .C (n_26), .Z (n_282));
  HS65_GSS_XOR3X2 g8012(.A (n_77), .B (n_36), .C (n_74), .Z (n_283));
  HS65_GS_DFPQX9 retime_s1_12_reg(.CP (rc_gclk), .D (B[5]), .Q (n_284));
  HS65_GSS_XNOR2X6 g8015(.A (n_190), .B (n_198), .Z (Z[7]));
  HS65_GSS_XOR3X2 g8016(.A (n_170), .B (n_157), .C (n_173), .Z (Z[5]));
  HS65_GS_PAO2X9 g8018(.A (n_29), .B (n_66), .P (n_109), .Z (n_288));
  HS65_GS_OA12X9 g8019(.A (n_45), .B (n_76), .C (n_92), .Z (n_289));
  HS65_GS_XOR3X9 g8020(.A (n_43), .B (n_69), .C (n_0), .Z (n_290));
endmodule

module RC_CG_MOD_AUTO_mac4_1(ck_in, enable, test, ck_out);
  input ck_in, enable, test;
  output ck_out;
  wire ck_in, enable, test;
  wire ck_out;
  wire enl, n_0;
  HS65_GS_LDLQX9 enl_reg(.GN (ck_in), .D (n_0), .Q (enl));
  HS65_GS_OR2X9 g11__3772(.A (test), .B (enable), .Z (n_0));
  HS65_GS_AND2X4 g17__1474(.A (ck_in), .B (enl), .Z (ck_out));
endmodule

module mac4(a, b, en, clk, reset, out);
  input [7:0] a, b;
  input en, clk, reset;
  output [15:0] out;
  wire [7:0] a, b;
  wire en, clk, reset;
  wire [15:0] out;
  wire [1:0] reg_en;
  wire [15:0] prod;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, n_0, n_1, n_2, n_3,
       n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_83, n_84, n_85, n_86, \out[0]_171 , \out[1]_172 , \out[2]_173
       , \out[3]_174 ;
  wire \out[4]_175 , \out[5]_176 , \out[6]_177 , \out[7]_178 ,
       \out[8]_179 , \out[9]_180 , \out[10]_181 , \out[11]_182 ;
  wire \out[12]_183 , \out[13]_184 , \out[14]_185 , rc_gclk, rc_gclk_88;
  RC_CG_MOD_AUTO_mac4 RC_CG_HIER_INST1(.ck_in (clk), .enable
       (reg_en[1]), .test (1'b0), .ck_out (rc_gclk));
  add_unsigned add_38_21(.A ({out[15:4], n_84, n_86, n_85, n_83}), .B
       (prod), .Z ({out[15], \out[14]_185 , \out[13]_184 , \out[12]_183
       , \out[11]_182 , \out[10]_181 , \out[9]_180 , \out[8]_179 ,
       \out[7]_178 , \out[6]_177 , \out[5]_176 , \out[4]_175 ,
       \out[3]_174 , \out[2]_173 , \out[1]_172 , \out[0]_171 }), .clk
       (clk), .Q (reg_en[1]), .reset (reset), .Q_1
       (UNCONNECTED_HIER_Z), .RC_CG_GCLK_PORT (rc_gclk_88));
  mult_unsigned mul_31_23(.A (a), .B (b), .Z (prod), .clk (clk), .en
       (en), .Q (UNCONNECTED_HIER_Z0), .RC_CG_GCLK_PORT (rc_gclk_88));
  RC_CG_MOD_AUTO_mac4_1 RC_CG_DECLONE_HIER_INST(.ck_in (clk), .enable
       (reg_en[0]), .test (1'b0), .ck_out (rc_gclk_88));
  HS65_GS_BFX35 g132(.A (n_84), .Z (out[3]));
  HS65_GS_BFX35 g131(.A (n_86), .Z (out[2]));
  HS65_GS_BFX35 g127(.A (n_85), .Z (out[1]));
  HS65_GS_BFX35 g133(.A (n_83), .Z (out[0]));
  HS65_GS_DFPRQX9 \reg_en_reg[1] (.RN (reset), .CP (clk), .D
       (reg_en[0]), .Q (reg_en[1]));
  HS65_GS_DFPRQX4 \reg_en_reg[0] (.RN (reset), .CP (clk), .D (en), .Q
       (reg_en[0]));
  HS65_GS_DFPRQNX9 retime_s3_12_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[2]_173 ), .QN (n_1));
  HS65_GS_DFPRQNX9 retime_s3_4_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[13]_184 ), .QN (n_12));
  HS65_GS_DFPRQNX9 retime_s3_16_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[6]_177 ), .QN (n_5));
  HS65_GS_DFPRQNX9 retime_s3_5_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[12]_183 ), .QN (n_11));
  HS65_GS_DFPRQNX9 retime_s3_6_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[11]_182 ), .QN (n_10));
  HS65_GS_DFPRQNX9 retime_s3_7_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[10]_181 ), .QN (n_9));
  HS65_GSS_DFPRQNX18 retime_s3_3_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[14]_185 ), .QN (n_13));
  HS65_GS_DFPRQNX9 retime_s3_13_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[4]_175 ), .QN (n_3));
  HS65_GS_DFPRQNX9 retime_s3_9_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[8]_179 ), .QN (n_7));
  HS65_GS_DFPRQNX9 retime_s3_10_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[7]_178 ), .QN (n_6));
  HS65_GS_DFPRQNX9 retime_s3_11_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[1]_172 ), .QN (n_0));
  HS65_GS_DFPRQNX9 retime_s3_8_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[9]_180 ), .QN (n_8));
  HS65_GS_DFPRQNX9 retime_s3_14_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[3]_174 ), .QN (n_2));
  HS65_GS_DFPRQNX9 retime_s3_15_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[5]_176 ), .QN (n_4));
  HS65_GS_DFPRQX9 retime_s3_17_reg(.RN (reset), .CP (rc_gclk), .D
       (\out[0]_171 ), .Q (n_83));
  HS65_GS_IVX35 g142(.A (n_13), .Z (out[14]));
  HS65_GS_IVX9 g143(.A (n_2), .Z (n_84));
  HS65_GS_IVX35 g144(.A (n_9), .Z (out[10]));
  HS65_GS_IVX35 g145(.A (n_10), .Z (out[11]));
  HS65_GS_IVX9 g146(.A (n_0), .Z (n_85));
  HS65_GS_IVX9 g147(.A (n_1), .Z (n_86));
  HS65_GS_IVX35 g148(.A (n_8), .Z (out[9]));
  HS65_GS_IVX53 g149(.A (n_4), .Z (out[5]));
  HS65_GS_IVX71 g150(.A (n_3), .Z (out[4]));
  HS65_GS_IVX35 g151(.A (n_12), .Z (out[13]));
  HS65_GS_IVX35 g152(.A (n_7), .Z (out[8]));
  HS65_GS_IVX35 g153(.A (n_11), .Z (out[12]));
  HS65_GS_IVX44 g154(.A (n_5), .Z (out[6]));
  HS65_GS_IVX35 g155(.A (n_6), .Z (out[7]));
endmodule

